title: Portfolio
description: A summary of projects I worked on
theme: just-the-docs
color_scheme: dark

url: https://https://mathematisse.github.io/Portfolio/

callouts:
  warning:
    title: Warning
    color: red
